services:
  backend:
    image: docker.io/uemcpa/relatorios-backend

  frontend:
    image: docker.io/uemcpa/relatorios-frontend
    volumes:
      - ./data:/data:rw
    environment:
      - API_URL=http://backend:5000/upload
    ports:
      - 8080:3000