name: Montagem das Imagens dos Containers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Montagem do frontend
      run: cd frontend && docker build . --file Dockerfile --tag relatorios-frontend:$(date +%s) && docker build . --file Dockerfile --tag relatorios-frontend:latest
    - name: Montagem do backend
      run: cd ../backend && docker build . --file Dockerfile --tag relatorios-backend:$(date +%s) && docker build . --file Dockerfile --tag relatorios-backend:latest
