name: Montagem das Imagens dos Containers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Montagem do frontend
      run: cd frontend && docker build . --file Dockerfile --tag relatorios-frontend:$(date +%s) && docker build . --file Dockerfile --tag relatorios-frontend:latest
    - uses: actions/checkout@v4
    - name: Instalação do Go
      run: cd backend && apt update && apt install -y golang
    - name: Montagem do binário
      run: go build main.go
    - name: Montagem do backend
      run: docker build . --file Dockerfile --tag relatorios-backend:$(date +%s) && docker build . --file Dockerfile --tag relatorios-backend:latest

